uktrade/invest-pir-api

investment_report/templates/admin/pir_request_list.html
Just adding a message to a template.
=> Cms 229/gdpr message on csv download

investment_report/templates/investment_report.html
I made case studies optional in the document, but I didn't update the TOC. Fixes this.
=> Fix TOC with optional case studies

config/settings/__init__.py, config/settings/testing.py, investment_report/admin.py, requirements.in, requirements.txt, requirements_test.txt
=> Login rate limiting

config/settings/__init__.py, config/urls.py, investment_report/templates/admin/unlock_account.html, investment_report/tests/test_admin.py, investment_report/views/auth.py
When the account has been locked out, the login page now redirects to an email prompt form. I've also enabled password reset emails.
=> Cms 268/account unlock

investment_report/templates/investment_report.html
This just makes a lot more aesthetic sense.
=> Swap round order of sector logos and market logos

investment_report/password_validation.py
=> Fix help text when adding user password

investment_report/templates/investment_report.html, static/src/investment-report.css
=> Front page title modifications

investment_report/admin.py
=> Improve admin

runtime.txt
=> update python version

CHANGELOG.md, requirements.in, requirements.txt, requirements_test.txt
=> CI-422: Update Django Version

requirements.in, requirements.txt, requirements_test.txt
=> XOT-1169 Upgrade notify library to 5.4.0

CHANGELOG.md, requirements.in, requirements.txt, requirements_test.txt
=> Staging release

CHANGELOG.md
=> Update changelog release 2019.11.25

runtime.txt
=> update python 3.6.9

CHANGELOG.md, requirements.in, requirements.txt, requirements_test.txt
=> CVE-2020-5236 & CVE-2020-7471 fixes

CHANGELOG.md
- [ x ] Changelog entry added.
=> Updates to changelog

CHANGELOG.md, investment_report/utils.py
Fix issue with moderated multi-page objects
=> 2021.01.04 - fix

requirements.in, requirements.txt, requirements_test.txt
=> Gp2 2869 upgrading invest pir api to django 2

package-lock.json
=> FE package upgrade

CHANGELOG.md, gulpfile.js, package-lock.json, package.json
=> Update FE requirements

requirements.in, requirements.txt
=> Pyjwt upgrade

.github/dependabot.yml
=> KLS-132 Enable depandabot PRs for security patches

CHANGELOG.md, requirements.in, requirements.txt, requirements_test.txt
=> KLS-234 upgrade pillow to 9.3.0

requirements.txt, requirements_test.txt
=> UAT and production release

requirements.in, requirements.txt
This PR upgrades the sqlparse package to version 0.4.4
=> Upgrade sqlparse to 0.4.4

CHANGELOG.md
=> Force rebuild of develop

CHANGELOG.md, config/settings/__init__.py, config/urls.py, docker-compose-test.yml, docker-compose.yml, investment_report/views/api.py, makefile, requirements.in, requirements.txt
=> Release to UAT and Production

requirements_test.txt
=> 2.9.3 release

manifest.yml, requirements.in, requirements.txt
cflinux4fs upgrade: This change will fix the version of cflinuxfs4
=> KLS-1441 cflinuxfs4 fixed in manifest.yml

makefile, requirements.in, requirements.txt, requirements_test.in, requirements_test.txt
This ticket makes a small amendment to the requirements_test folder to upgrade package due to a vulnerability report.
=> AMENDED requirements_test files for bug upgrades

config/settings/__init__.py, config/urls.py, core/middleware.py, investment_report/admin.py, investment_report/templatetags/custom_media.py, investment_report/tests/test_util_views.py, investment_report/urls.py, requirements.in, requirements.txt, requirements_test.txt
=> KLS-1770 Upgrade Django for invest-pir-api

config/settings/__init__.py, config/urls.py, core/middleware.py, investment_report/admin.py, investment_report/templatetags/custom_media.py, investment_report/tests/test_util_views.py, investment_report/urls.py, requirements.in, requirements.txt, requirements_test.txt
=> UAT / PROD release 

requirements.in, requirements.txt, requirements_test.in, requirements_test.txt
=> update jinja2 to 3.1.3

.github/CODEOWNERS, requirements.in, requirements.txt, requirements_test.txt
(Please add a sentence or two explaining the context of this PR. Reviewers can go to the ticket for detail.)
CONTEXT: This changeset adds/removes/updates [summary of feature/area/code] so that [summary of benefit].
_Tick or delete as appropriate:_
=> Release to master
